Models/UserProfileClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace webt.Models
{
    public class UserProfileClass
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [MinLength(8)]
        public string Password { get; set; }
        public string Views { get; set; }
        public string ReturnView()
        {
            string View;
            View = " "; 
            if ((Email=="narmbuyu@gmail.com") && (Password=="123456789"))
            {
                View = "Admin";
            }
            if ((Email == "ayanda@gmail.com") && (Password == "123456789"))
            {
                View = "Technician";
            }
            else if ((Email == "rovanya@gmail.com") && (Password == "123456789"))
            {
                View = "Customer";
            }
            return (View);
        }
        
    }
}

Controllers/CustDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webt.Controllers
{
    public class CustDashboardController : Controller
    {
        // GET: CustDashboard
        public ActionResult CustomerDash()
        {
            return View();
        }
    }
}

Controllers/TController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webt.Controllers
{
    public class TController : Controller
    {
        // GET: T
        public ActionResult TE()
        {
            return View();
        }
    }
}

Controllers/TecDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webt.Controllers
{
    public class TecDashboardController : Controller
    {
        // GET: TecDashboard
        public ActionResult TechnicianDash()
        {
            return View();
        }
    }
}

Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webt.Models;

namespace webt.Controllers
{
    public class UserProfileController : Controller
    {
        // GET: SignUp
        public ActionResult SignUp()
        {
            return View();
        }

        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]

        public ActionResult LogIn(UserProfileClass LogingIn)
        {
            LogingIn.Views = LogingIn.ReturnView();
            return View(LogingIn);
        }
        public ActionResult ForgotPassword()
        {
            return View();
        }

        
    }
}

//public ActionResult LogIn(UserProfileClass LogingIn)
//{
//    LogingIn.Views = LogingIn.ReturnView();

//    if (LogingIn.Email == "email@gmail.com" && LogingIn.Password == "password123")
//    {
//        ViewBag["IsSuccess"] = true;
//    }
//    else
//    {
//        ViewBag["IsSuccess"] = ;
//    }

//    return View(LogingIn);
//}

Views/UserProfile/ForgotPassword.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Forget Password</title>

    <!-- Fontfaces CSS-->
    <link href="~/Dashboard/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/Dashboard/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/Dashboard/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Dashboard/css/theme.css" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="~/Dashboard/images/icon/logo.png" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">
                            <form action="" method="post">
                                <div class="form-group">
                                    <label>Email Address</label>
                                    <input class="au-input au-input--full" type="email" name="email" placeholder="Email">
                                </div>
                                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="~/Dashboard/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/Dashboard/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Dashboard/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="vendor/slick/slick.min.js">
    </script>
    <script src="~/Dashboard/vendor/wow/wow.min.js"></script>
    <script src="~/Dashboard/vendor/animsition/animsition.min.js"></script>
    <script src="~/Dashboard/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/Dashboard/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Dashboard/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/Dashboard/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Dashboard/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Dashboard/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Dashboard/vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="~/Dashboard/js/main.js"></script>

</body>

</html>
<!-- end document-->

Views/UserProfile/LogIn.cshtml
@model webt.Models.UserProfileClass
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Login</title>

    <!-- Fontfaces CSS-->
    <link href="~/Dashboard/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/Dashboard/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/Dashboard/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Dashboard/css/theme.css" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="~/Dashboard/images/icon/logo.png" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">
                            <form action="" method="post">
                                <div class="form-group">
                                    <label>Email Address</label>
                                    <input class="au-input au-input--full" type="email" name="email" placeholder="Email" @Html.EditorFor(Email => Email.Email)
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input class="au-input au-input--full" type="password" name="password" placeholder="Password" @Html.EditorFor(Password => Password.Password)
                                </div>
                                <div class="login-checkbox">
                                    <label>
                                        <input type="checkbox" name="remember">Remember Me
                                    </label>
                                    <label>
                                        <a href="@Url.Action("ForgotPassword","UserProfile")">Forgotten Password?</a>
                                    </label>
                                </div>
                                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">sign in</button>
                                
                                @*@if (Model.Views == "Admin")
                                {
                                    @Url.Action("AdminDash", "AdminDashboard")
                                }
                                @if (Model.Views == "Technician")
                                {
                                    @Url.Action("TechnicianDash", "TecDashboardController")
                                }
                                else if (Model.Views == "Technician")
                                {
                                    @Url.Action("CustomerDash", "CustDashboardController")
                                }*@
                                <div class="social-login-content">
                                    <div class="social-button">
                                        <button class="au-btn au-btn--block au-btn--blue m-b-20">sign in with facebook</button>
                                        <button class="au-btn au-btn--block au-btn--blue2">sign in with twitter</button>
                                    </div>
                                </div>
                            </form>
                            <div class="register-link">
                                <p>
                                    Don't you have account?
                                    <a href="@Url.Action("SignUp","UserProfile")">Sign Up Here</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="~/Dashboard/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/Dashboard/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Dashboard/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/Dashboard/vendor/slick/slick.min.js">
    </script>
    <script src="~/Dashboard/vendor/wow/wow.min.js"></script>
    <script src="~/Dashboard/vendor/animsition/animsition.min.js"></script>
    <script src="~/Dashboard/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/Dashboard/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Dashboard/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/Dashboard/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Dashboard/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Dashboard/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Dashboard/vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="~/Dashboard/js/main.js"></script>

</body>

</html>
<!-- end document-->

Views/UserProfile/SignUp.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Register</title>
    @* css/font-face.css*@
    <!-- Fontfaces CSS-->
    <link href="~/Dashboard/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/Dashboard/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/Dashboard/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Dashboard/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Dashboard/css/theme.css" rel="stylesheet" media="all">



</head>

<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="~/Dashboard/images/icon/logo.png" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">
                            <form action="" method="post">
                                <div class="form-group">
                                    <label>Username</label>
                                    <input class="au-input au-input--full" type="text" name="username" placeholder="Username">
                                </div>
                                <div class="form-group">
                                    <label>Email Address</label>
                                    <input class="au-input au-input--full" type="email" name="email" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input class="au-input au-input--full" type="password" name="password" placeholder="Password">
                                </div>
                                <div class="login-checkbox">
                                    <label>
                                        <input type="checkbox" name="aggree">Agree the terms and policy
                                    </label>
                                </div>
                                <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">register</button>
                                <div class="social-login-content">
                                    <div class="social-button">
                                        <button class="au-btn au-btn--block au-btn--blue m-b-20">register with facebook</button>
                                        <button class="au-btn au-btn--block au-btn--blue2">register with twitter</button>
                                    </div>
                                </div>
                            </form>
                            <div class="register-link">
                                <p>
                                    Already have account?
                                    <a href="@Url.Action("LogIn","UserProfile")">Sign In</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="~/Dashboard/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/Dashboard/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Dashboard/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/Dashboard/vendor/slick/slick.min.js">
    </script>
    <script src="~/Dashboard/vendor/wow/wow.min.js"></script>
    <script src="~/Dashboard/vendor/animsition/animsition.min.js"></script>
    <script src="~/Dashboard/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/Dashboard/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Dashboard/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/Dashboard/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Dashboard/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Dashboard/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Dashboard/vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="~/Dashboard/js/main.js"></script>

</body>

</html>
<!-- end document-->